### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem#3]
A backlog for the [Version 2.0.0](https://github.com/arcticicestudio/northem/milestone/2) milestone.
The whole project, including both sub-palettes and related sub-rpojects/ports, should be rewritten and cleaned up to adapt to the new project setup like the [Nord](https://github.com/arcticicestudio/nord) project.
## Sub-Issues

All sub-issues are listed below and will be merged into the main milestone branch [`release/ghi-#3-2.0.0`](https://github.com/arcticicestudio/northem/tree/release/ghi-%233-2.0.0).
- [x] #5 Rewrite Sass sources
- [x] #8 Travis CI and Circle CI build integration
- [x] #6 Rewrite LESSCSS sources
- [x] #7 Recreate native format files
- [x] #10 NPM package.json file
- [x] #9 Gulp project file
- [x] #4 Adapt new project setup and documentation style
### Naming Scheme

**Color names**
The current naming scheme, where each color got an individual name based on the value, will be replaced with an numbered format.
Example: `darkest-gray` will be renamed to `northem0`, `dark-gray` to `northem1`.
This will continue with a continuous numerating where the current position of a color represents its number.

**Components**
Next to this, the color palette will be divided into four named components to represent the different color effects where each component contains a different amount of colors:  
1. **Dark Water** `northem0` - `northem3`  
2. **Light Wind** `northem4` - `northem6`  
3. **Ice** `northem7` - `northem10`  
4. **Rainbow** `northem11` - `northem15`

This naming convention allows an uncomplicated use for terminals and preserves the compatibility to similar projects like [base16](chriskempson.com/projects/base16).

The X11 color scheme names and RGB value variables will be removed, but X11 color names will be included in the Sass- and LESSCSS source documentations.
### New color

A new color will be added to close the gap of the missing sixteenth color.
The value of the color is `#CACACA` and will be added to the _Light Wind_ component.
This color is calculated from the components base color `#DEDEDE` via the Sass method `darken(#DEDEDE, 8%)`.
### Source Formats

**Sass**
All [Sass](http://sass-lang.com)  sources will be documented via [SassDoc](http://sassdoc.com) and a `template-css.scss` will be available to compile a CSS file with all color variables which is cimpatible to the CSS specification.
The SassDoc will be configurable via the `.sassdocrc` file.

**LESSCSS**
All [LESSCSS](http://lesscss.org) sources will be documented via [KSS](http://warpspire.com/kss).

**Native**
All native files will be recreated containing the new color and new color naming scheme.
### Build Tools

**Gulp**
Introduce a [Gulp](gulpjs.com) file to compile Sass sources to CSS, provide a local live-server by watching the filesystem for changes and build the new [SassDoc](http://sassdoc.com).
This will result in the following NPM `devDependencies`:  

``` json
    "del": "2.2.2",
    "gulp": "3.9.1",
    "gulp-help": "1.6.1",
    "gulp-plumber": "1.1.0",
    "gulp-rename": "1.2.2",
    "gulp-sass": "2.3.2",
    "gulp-util": "3.0.7",
    "sassdoc": "2.1.20",
    "sassdoc-theme-flippant": "0.1.0"
```

**Travis CI and Circle CI**
Add `.travis.yml` and `circle.yml` configuration files for continous integration web services.
### NPM

A `package.json` file will be added to provide project meta data and dependencies for a release as a Node.js package.
### Assets

All project branding assets will be removed and replaced with the new, modern SVG and AI files.
### Documentations

All project documentations will be rewritten like the `README.md`, `CHANGELOG.md` and `LICENSE.md`.
The project license for the code will be changed to the Apache 2.0 license.
### Git

The `.gitignore` and `.gitattributes` files will be rewritten to remove the high amount of unused pattern and doccomments.
