### ISSUE TITLE
Adapt new project setup and documentation style

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem#4]
**Tasks**
- [x] Refactor the `.gitignore` and `.gitattributes` files
- [x] Delete the `odin.json` and `repository.assk` files
- [x] Update the `README.md`, `CHANGELOG.md` and `LICENSE.md` files to the new documentation style
- [x] Remove the `COPYRIGHT.md` file
- [x] Move to the Apache 2.0 license
- [x] Remove old assets
- [x] Add the new project branding assets (SVG and AI files)

Detailed information can be found in the milestone backlog issue #3.
