### ISSUE TITLE
Rewrite Sass sources

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem#5]
### Tasks
- [x] Rename all variables to the new naming scheme
- [x] Write SassDoc
- [x] Add the new color
- [x] Implement the `template-css.scss` file
- [x] Move files to the new `src/sass` directory

Detailed information can be found in the milestone backlog issue #3.
