### ISSUE TITLE
Rewrite LESSCSS sources

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem#6]
### Tasks
- [x] Rename all variables to the new naming scheme
- [x] Add the new color
- [x] Write KSS documentation
- [x] Move file to the new `src/lesscss` directory

Detailed information can be found in the milestone backlog issue #2.
