### ISSUE TITLE
Create native format files

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem#7]
**Tasks**
- [x] Create "Adobe Photoshop Color Palette" file
- [x] Create "Adobe Swatch exchange" file
- [x] Create "Gpick Palette" file 
- [x] Create "GIMP/Inkscape/CinePaint/Krita Palette" file
- [x] Create "Alias/WaveFront Material" file

Detailed information can be found in the milestone backlog issue #3.
