### ISSUE TITLE
Gulp project file

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem#9]
:grey_exclamation: This feature depends on the NPM `package.json` file and must be implemented after #10 :grey_exclamation: 

**Tasks**
- [x] Implement the [gulpfile](http://gulpjs.com)
  - [x] Implement `clean` task
  - [x] Implement `clean-css` task
  - [x] Implement `clean-documentation` task
  - [x] Implement `compile-css-template` task
  - [x] Implement `default` task which calls the `help` plugin
  - [x] Implement `sassdoc` task

**Dependencies**
`npm` packages:  

``` json
    "del": "2.2.2",
    "gulp": "3.9.1",
    "gulp-help": "1.6.1",
    "gulp-plumber": "1.1.0",
    "gulp-rename": "1.2.2",
    "gulp-sass": "2.3.2",
    "gulp-util": "3.0.7",
    "sassdoc": "2.1.20",
    "sassdoc-theme-flippant": "0.1.0"
```

Detailed information can be found in the milestone backlog issue #3.
